services:
  - type: web
    name: voicefusion
    env: python
    buildCommand: pip install -r requirement.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      PYTHON_VERSION: 3.10.13